// Service worker for the built client — generated by vite.config.ts
// (`elyxionBuildMeta`): __VERSION__ is the build id (also stamped into
// index.html's `elyxion-build` meta) and __PRECACHE__ the hashed app chunks, so
// every deployment ships a byte-different sw.js and the browser always picks it
// up. The game's own updater (src/update-checker.ts) decides WHEN to reload —
// this worker never force-reloads, so a running match is never interrupted.
//
// Strategy:
//   • install  — precache the shell + hashed JS/CSS chunks (the app can't run
//                without them). Models/sounds/fonts are cached on first use.
//   • activate — delete caches from older builds (skewed hashes / bloat gone).
//                No skipWaiting: the new worker takes over at the next reload
//                boundary the updater chooses, never mid-match. clients.claim
//                only ever matters on FIRST install (no old worker to fight),
//                where it makes the already-open tab cache things immediately.
//   • fetch    — /assets/* + other same-origin static: cache-first, network
//                fill (hashed = immutable; stable files benefit from the server
//                headers too). index.html (navigations AND the updater's poll
//                fetch, detected via Accept: text/html): network-first, falling
//                back to the cached shell so ANY offline route (/, /play, …)
//                loads the SPA. /api/* and /ws/* are never touched — the game
//                socket and API must always be live.

const VERSION = '__VERSION__';
const PRECACHE = __PRECACHE__;
const CACHE_NAME = 'elyxion-' + VERSION;
const SHELL = '/';
const ASSET_RE = /(?:src|href)="((?:\/assets\/)[^"]+\.(?:js|css))"/g;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE))
      // A mid-deploy install must never block activation of the worker.
      .catch(() => {}),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((k) => k.startsWith('elyxion-') && k !== CACHE_NAME)
            .map((k) => caches.delete(k)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

// Fetch a URL and store it in the current cache (best-effort — used to warm the
// new build's chunks the moment a fresh index.html is seen).
function warm(url) {
  fetch(url)
    .then((res) => {
      if (res.ok && res.type === 'basic') {
        const copy = res.clone();
        caches
          .open(CACHE_NAME)
          .then((c) => c.put(url, copy))
          .catch(() => {});
      }
    })
    .catch(() => {});
}

// Cache-first with network fill for immutable/static same-origin assets.
async function cacheFirst(req) {
  const hit = await caches.match(req).catch(() => null);
  if (hit) return hit;
  const res = await fetch(req);
  if (res.ok && res.type === 'basic') {
    const copy = res.clone();
    caches
      .open(CACHE_NAME)
      .then((c) => c.put(req, copy))
      .catch(() => {});
  }
  return res;
}

// index.html: always prefer the network (fresh deploys), fall back to the
// cached shell when offline. The shell is stored under a constant key so a
// deep route like /play or /support can fall back too (SPA).
async function networkFirstHtml(req) {
  try {
    const res = await fetch(req);
    if (res.ok && res.type === 'basic') {
      const html = await res.clone().text();
      const cache = await caches.open(CACHE_NAME);
      await cache.put(SHELL, new Response(html, { headers: { 'Content-Type': 'text/html' } }));
      // Warm the new build's chunks in the background → the updater's reload is
      // a cache hit instead of a stutter.
      for (const m of html.matchAll(ASSET_RE)) warm(m[1]);
    }
    return res;
  } catch {
    const cache = await caches.open(CACHE_NAME);
    const hit = await cache.match(req).catch(() => null);
    if (hit) return hit;
    const shell = await cache.match(SHELL).catch(() => null);
    if (shell) return shell;
    return new Response(
      'Elyxion is offline and not cached yet — load the site once while online, then it keeps working offline.',
      { status: 503, headers: { 'Content-Type': 'text/plain' } },
    );
  }
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  const path = url.pathname;

  // Never touch the API or the game/other websockets. sw.js itself is fetched
  // by the browser for update checks — serve it straight from the network.
  if (path === '/sw.js' || path.startsWith('/api/') || path.startsWith('/ws/')) return;

  const wantsHtml =
    req.mode === 'navigate' || (req.headers.get('accept') || '').includes('text/html');
  if (wantsHtml) {
    event.respondWith(networkFirstHtml(req));
  } else {
    event.respondWith(cacheFirst(req));
  }
});